### ISSUE TITLE
trying to get property of non-object

### ISSUE THREAD

**Issue by wpbullet** [lcache/wp-lcache#104]
Seeing this with wp_debug set to on

```Notice: Trying to get property of non-object in /var/www/woocommerce/wp-content/plugins/wp-lcache/vendor/lcache/lcache/src/APCuL1.php on line 43```

**Comment by danielbachhuber** [comment]
@wpbullet Is this on a Pantheon site?

This could actually be related to https://github.com/pantheon-systems/wp-native-php-sessions/issues/49

**Comment by wpbullet** [comment]
This is self-hosted on a Digital Ocean droplet running php7 and nginx.

**Comment by danielbachhuber** [comment]
Interesting! Any chance we could get a `debug_backtrace()` out of the error so we could see where it's coming from?

**Comment by wpbullet** [comment]
If I knew how to do that then yes :) If you have a walkthrough I'd be happy to oblige. I can also share the admin or root credentials via email if you prefer. I'm a wp profile user so I have your email already.

**Comment by danielbachhuber** [comment]
Could you ping me on the WordPress.org Slack? Might be easiest to chat through this first.

**Comment by wpbullet** [comment]
Pinged you there

**Comment by danielbachhuber** [comment]
This was a bad value in APCu. The fix was to restart PHP-FPM
