### ISSUE TITLE
First view takes 1 second more whn plugin is activated

### ISSUE THREAD

**Issue by abumalick** [lcache/wp-lcache#106]
Hello,
I just managed to install the plugin and tested the speed to see if it works.
I desactive cloudflare and run the tests on www.webpagetest.org .
When the plugin is not active the first bite takes 0.220s
When the plugin is enabled, the first bite takes 0.799s
I don't know why ..

> First Byte Time:	
> - Applicable Objects : Time to First Byte for the page (back-end processing + redirects)
> - What is checked : The target time is the time needed for the DNS, socket and SSL negotiations + 100ms. A single letter grade will be deducted for every 100ms beyond the target.

Please note that I use [bedrock wordpress boilerplate](https://roots.io/bedrock/) and it has different directory structure than normal wordpress installation.
So the path in `object-cache.php` : 
`$lcache_path = dirname( realpath( __FILE__ ) ) . '../../app/plugins/wp-lcache/object-cache.php';`

If you need more info, please let me know.

**Comment by danielbachhuber** [comment]
Sorry to hear you're having trouble with the plugin. Based on these details, it's not clear to me what the issue might be unfortunately.

Here are some questions to help dig deeper:

1. Did you run the Web Page Test immediately after enabling WP LCache, or did you visit some pages on the website beforehand?
2. Have you run subsequent tests on Web Page Test? If so, was the time to first byte consistent? If not, can you run additional tests to see if the time to first byte is consistent?
3. Is your database on the same machine, or a different machine? Could you share more details about your server architecture?
4. What sort of plugins and custom code are you running?

**Comment by abumalick** [comment]
Sorry for late reply, I am busy at the moment.

> 1. Did you run the Web Page Test immediately after enabling WP LCache, or did you visit some pages on the website beforehand?

I runned the test directly

> 2.  Have you run subsequent tests on Web Page Test? If so, was the time to first byte consistent? If not, can you run additional tests to see if the time to first byte is consistent?

I tried 2 or 3 times and it was about the same time.

> 3. Is your database on the same machine, or a different machine? Could you share more details about your server architecture?

Database on localhost, The provider is o2switch, they offer shared hosting with ssh/composer/git/... We have a cpanel. It uses apache + php7 + maria db.

> 4. What sort of plugins and custom code are you running?

    package-list

**Comment by danielbachhuber** [comment]
Ok. You've got a lot of extra code running there.

Does the issue reproduce in the same environment, but with a stock WordPress install (e.g. no additional plugins active, and using a default theme)?

**Comment by abumalick** [comment]
I will eventually try this
