### ISSUE TITLE
Use Redis for L2 cache

### ISSUE THREAD

**Issue by ahmed-sigmalux** [lcache/wp-lcache#146]
Great idea on using a high speed APCu L1 cache with a shared L2 cache, but I think your choice of MySQL for L2 IS suboptimal. Of all the datastores in our server stack, MySQL is by far the slowest and has the highest latency.

Wouldn't it make more sense to use Redis, Memcache, or the like for the L2 cache? You'd get all the benefits of a shared L2 cache but at a much lower latency and a higher speed. You'd also avoid gunking up your database or slowing down other database transactions while warming the L1 cache(s).

**Comment by danielbachhuber** [comment]
Thanks for the feedback @ahmed-sigmalux !

> Wouldn't it make more sense to use Redis, Memcache, or the like for the L2 cache?

If I recall correctly (but I'm not 100% sure), there were some features of MySQL that Redis doesn't implement directly.

Under the hood, WP LCache uses the LCache library. Feel free to open a new issue about using Redis as a L2: https://github.com/lcache/lcache/issues There are also a number of pull requests, issues, etc. with good history on the design decisions for the project.
