### ISSUE TITLE
Database table creation can fail with error "Specified key was too long; max key length is 1000 bytes"

### ISSUE THREAD

**Issue by danielbachhuber** [lcache/wp-lcache#148]
```
WordPress database error Specified key was too long; max key length is 1000 bytes for query CREATE TABLE IF NOT EXISTS
```

From https://wordpress.org/support/topic/lcache-database-tables-not-created/

**Comment by danielbachhuber** [comment]
`SHOW VARIABLES` on the offending server: https://gist.github.com/ramontolkamp/8e1d5b2402217222f519312da5d640ae

**Comment by danielbachhuber** [comment]
@fjarrett Do you recall why you changed `address` to `varchar(191)` on the `tags` table but not the `events` table (#131)?

**Comment by danielbachhuber** [comment]
Based on [this](https://stackoverflow.com/a/40110286/6800777) and [this](https://stackoverflow.com/a/8747703/6800777), my understanding is that the error happens because Barracuda is not enabled for MySQL, which means our index key length is too long for stock InnoDB.

If it's a problem we want to solve, we could work around this by setting prefix lengths to each column. Alternatively, we can show a warning when Barracuda isn't enabled.

**Comment by frankiejarrett** [comment]
@danielbachhuber I think `address` was left as `varchar(255)` because it isn't an indexed column in the `events` table, but on the `tags` table it's the `PRIMARY KEY`. In my testing of that feature I was only seeing the error on indexed columns.

**Comment by danielbachhuber** [comment]
> If it's a problem we want to solve, we could work around this by setting prefix lengths to each column. Alternatively, we can show a warning when Barracuda isn't enabled.

We could also change `events.address` to `varchar(171)` (accommodating `bigint(20)` for `event_id`), but I wonder if that's too short.

**Comment by danielbachhuber** [comment]
Looking into this even further, I think we can revert the utf8mb4 charset on creation because our `value` column is `LONGBLOB`, which is binary and doesn't use charsets.

**Comment by danielbachhuber** [comment]
🔨
