### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by fl4p** [lcache/wp-lcache#153]
On my site I benchmarked some object caches (median of ~500 continuous requests):

![image](https://user-images.githubusercontent.com/2705942/31500330-6a145946-af67-11e7-948e-2490713c5337.png)
As you can see wp-lcache actually slows down.

And I benchmarked wp-lcache interface (single request):

![image](https://user-images.githubusercontent.com/2705942/31500301-58514318-af67-11e7-9e22-7065773f94fb.png)

I did not stick into the code. It looks like `get()` has a minimum latency during the request 

```
PHP Version 7.0.23-1+ubuntu16.04.1+deb.sury.org+1
```

![image](https://user-images.githubusercontent.com/2705942/31500675-560db37e-af68-11e7-87c3-3968f943fdf2.png)

Is it wp-lcache or anything wrong with my APCu?

**Comment by danielbachhuber** [comment]
Thanks for opening the issue, @f4bsch.

Some follow up questions:

1. Is this benchmarked against a stock WordPress install, or one with lots of themes/plugins active?
2. Is your benchmarking with APCu primed? WP LCache is a two-tier cache: the first request will always hit the database (which is almost certainly slower than connecting to Redis on the same machine), and then the second request will hit the local APCu cache.

**Comment by fl4p** [comment]
@danielbachhuber ,
1) Its a WP 4.8.2 with 10 plugins, 1 Theme. No chubby plugins like WooCommerce
2) It should be, it were 500 requests. On the server I measured the time PHP runs to generate a single response (`$_SERVER['REQUEST_TIME_FLOAT']` until `microtime(true)` at PHP shutdown). I then computed  the median from 500 requests.

**Comment by danielbachhuber** [comment]
@f4bsch Interesting.

I don't think your benchmarks are quite correct, but it's hard to say what the actual problem is without being able to explore at depth. It seems like something may be misconfigured.

**Comment by fl4p** [comment]
@danielbachhuber What makes you think my benchmarks are not correct?
If you think there is a misconfiguration, why did you close this issue?

**Comment by danielbachhuber** [comment]
> What makes you think my benchmarks are not correct?

In an optimal configuration, WP LCache should perform (and has been tested to perform) much better than indicated.

> If you think there is a misconfiguration, why did you close this issue?

The scope of our FOSS support is limited to bugs with documented reproduction steps.

**Comment by fl4p** [comment]
Where are these benchmarks?

Well here are the steps to reproduce:
1. Setup a VPS (it has to be a capped virtual CPU) with nginx, PHP 7, APCu, MariaDB 
2. Install WordPress and wp-lcache
3. Use e.g. http://www.bytecheck.com/ to make 5 measurements with/without wp-lcache and take the median
