### ISSUE TITLE
[INQUIRY] - Status of this project as of 2019?

### ISSUE THREAD

**Issue by wkhayrattee** [lcache/wp-lcache#158]
Hey there @danielbachhuber , @joshkoenig and Pantheon team.

1) As of now, Apr 2019, what's the status with this plugin?
2) Is Pantheon still using it on its infrastructure, if not what are you using now?

Asking, because some issues here dating 2017 has not been resolved yet and the last real code change "commit" probably was 2yrs ago.

This plugin, as I once mentioned, seemed very promising. But if it is no more active and not making sense, kindly communicate it upfront to prevent people investing time on deploying this. ;) But I am hoping all is well.

Also, an additional question if I may ask:
3) On Pantheon's server infrastructure, you don't use Redis or Nginx revers proxy caching?
I read [here](https://pantheon.io/wordpress/cache-plugins) that it uses Varnish with Wp-Lcache - want to confirm if this is still the same?

Cheers.

**Comment by danielbachhuber** [comment]
Hi @7php,

Thanks for the issue.

> 1. As of now, Apr 2019, what's the status with this plugin?

It's available for use with one significant known issue #138

> 2. Is Pantheon still using it on its infrastructure, if not what are you using now?

No, LCache isn't in wide deployment. WP Redis is the recommended persistent object cache: https://github.com/pantheon-systems/wp-redis

> This plugin, as I once mentioned, seemed very promising. But if it is no more active and not making sense, kindly communicate it upfront to prevent people investing time on deploying this. ;)

Do you have any recommendations on how this could be communicated?

> 3. On Pantheon's server infrastructure, you don't use Redis or Nginx revers proxy caching?
I read here that it uses Varnish with Wp-Lcache - want to confirm if this is still the same?

I'm not sure where it mentions Varnish with WP-LCache on that document. Here's the most up-to-date resource on Pantheon's full-page cache https://pantheon.io/global-cdn

**Comment by wkhayrattee** [comment]
Hi @danielbachhuber 
thank you for the awesome reply.

> >> Do you have any recommendations on how this could be communicated?

I think an updated message on the plugin repo itself - on the [readme of the github repo](https://github.com/lcache/wp-lcache) + on [the WP plugin page](https://wordpress.org/plugins/wp-lcache/), where you can advise users that due to that issue, the recommended approach is to use the WP Redis.

I appreciate and love all that you and the Pantheon are doing. Simply brilliant.

cheers

**Comment by danielbachhuber** [comment]
> I think an updated message on the plugin repo itself - on the readme of the github repo + on the WP plugin page, where you can advise users that due to that issue, the recommended approach is to use the WP Redis.

Thanks for the suggestion, @7php 

@davidstrauss Are you amenable to this?

**Comment by davidstrauss** [comment]
@danielbachhuber I think that's a good recommendation at this juncture.

**Comment by wkhayrattee** [comment]
cheers @danielbachhuber 
(thank you @davidstrauss )
