### ISSUE TITLE
Refer upstream

### ISSUE THREAD

**Issue by szepeviktor** [lcache/wp-lcache#16]
Could you refer upstream and add this to the readme?

> LCache is a module that applies the tiered caching model of multi-core processors (with local L1 and central L2 caches) to web applications. The current production implementation uses APCu as L1 and the database as L2.

It took me **minutes** to figure out what "L" cache is.

**Comment by danielbachhuber** [comment]
> Could you refer upstream and add this to the readme?

Yep, we'll add more documentation when it's available. The upstream actually hasn't been published as a public project yet.
