### ISSUE TITLE
Run integration tests against Pantheon

### ISSUE THREAD

**Issue by danielbachhuber** [lcache/wp-lcache#4]
Just like we have for the other Pantheon plugins, we should integration tests against Pantheon.
- [x] Set up Circle CI (Steve Persch will make Pantheon test user/site, Terminus Token, SSH keys, etc)
- [x] Run plugin specific tests
- [x] Run upstream tests (See https://github.com/pantheon-systems/solr-power/pull/107/files for an example)

**Comment by stevector** [comment]
I've started on the CircleCI set up. CircleCI is watching, Terminus tokens are set up, as are SSH keys.

**Comment by stevector** [comment]
A branch is started here: https://github.com/pantheon-systems/wp-lcache/pull/7
