### ISSUE TITLE
Gracefully Handle object-cache.php w/o DB tables, etc

### ISSUE THREAD

**Issue by joshkoenig** [lcache/wp-lcache#61]
If you deploy this plugin to a new environment, it will come inclusive of the `object-cache.php` symlink, but it will not be enabled in that new environment. This can cause a flood of errors about the LCache DB table not existing. We should handle this gracefully with a nice admin message.

Kind of the inverse of https://github.com/lcache/wp-lcache/issues/50

**Comment by danielbachhuber** [comment]
> This can cause a flood of errors about the LCache DB table not existing.

What's a good way of knowing whether or not the database table exists, without running a SQL query for it?

**Comment by joshkoenig** [comment]
We could test for whether the plugin is enabled?
