### ISSUE TITLE
Stuck Re-Doing WP Core Update Database Changes

### ISSUE THREAD

**Issue by joshkoenig** [lcache/wp-lcache#62]
Report from the field that a user was locked out of wp-admin when performing the core update. It would say "you need to update your db", which would succeed, but then the users were bounced to the homepage. Returning to `wp-admin` bounced them to the same warning about needing to run the database updates.

The eventual solution was to flush apc via `apc.php`.

We should see if this is replicable.

**Comment by danielbachhuber** [comment]
It looks like `wp_upgrade()` has a couple calls to `wp_cache_flush()`:

![image](https://cloud.githubusercontent.com/assets/36432/18530739/ccb41ff2-7a87-11e6-9ebe-7e15adc66e6d.png)

**Comment by joshkoenig** [comment]
Yep we should re-test this now that cache flushing is fixed. :tada:
